name: build
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install openscad
        run: sudo apt-get install -y openscad
      - name: install fonts
        run: sudo cp ./fonts/* /usr/share/fonts/ && sudo fc-cache -f -v
      - name: build
        run: chmod +x ./build.sh && ./build.sh release
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stls
          path: ./build/release/*.stl
